### ISSUE TITLE
Spotify API Research

### ISSUE THREAD

**Issue by anxsaiyuki** [IndecipherableSuggestions/RoadTripify#3]

**Comment by englundn** [comment]
Some potential issues:
There is a limit on the number of API requests we can make per minute. Generating a playlist may require many requests to get different songs from different playlists. We may want to cache data from Spotify's playlists in order to cut down on the number of requests.  There are endpoints that allow us to grab multiple songs at once.
Reference: https://developer.spotify.com/web-api/endpoint-reference/
